CREATE TABLE trainer_signup(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    id_card_number VARCHAR(13) NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    gender ENUM('ชาย', 'หญิง', 'อื่นๆ') NOT NULL,
    level_2 VARCHAR(100),
    level_3 VARCHAR(100),
    level_4 VARCHAR(100),
    level_5 VARCHAR(100),
    level_6 VARCHAR(100),
    start_year_2 INT,
    start_year_3 INT,
    start_year_4 INT,
    start_year_5 INT,
    start_year_6 INT,
    end_year_2 INT,
    end_year_3 INT,
    end_year_4 INT,
    end_year_5 INT,
    end_year_6 INT,
    district VARCHAR(100) NOT NULL,
    subdistrict VARCHAR(100) NOT NULL,
    image_profile VARCHAR(255),  
    image VARCHAR(255)
);